{% set name = "make-sense" %}
{% set version = "1.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/SkalskiP/make-sense/archive/{{ version }}-alpha.tar.gz
  sha256: cbe49b786de2b4fc4290adafb0af396608fb7ddd878e88259437310d749f93a8

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*/libgcc_s.so.1'
    - '*/libstdc++.so.6'

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - npm list -g {{ name }}

about:
  home: https://github.com/SkalskiP/make-sense
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Free to use online tool for labelling photos.
  doc_url: https://www.makesense.ai/
  dev_url: https://github.com/SkalskiP/make-sense

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
